appName: mb-service-3
replicaCount: 5
environment: prod
image:
    imageName: 693885100167.dkr.ecr.us-east-2.amazonaws.com/master-builder/sample-service-3
    imageTag: v10
    pullPolicy: Always
namespace: ns-master-builder-3
riskLevel: low-risk
