apiVersion: v1
kind: Service
metadata:
  name: {{ template "mb-service-3.fullname" . }}
  labels:
    app: {{ template "mb-service-3.name" . }}
    chart: {{ template "mb-service-3.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "mb-service-3.name" . }}
    release: {{ .Release.Name }}
